const $=id=>document.getElementById(id);
let apiBase='',token='',rows=[],timer;
const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
async function request(path,body){const r=await fetch(apiBase+'/api/admin/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw Error(data.error||'Admin request failed.');return data;}
function renderRows(){const q=$('filter').value.toLowerCase();$('chats').replaceChildren();for(const row of rows.filter(r=>(r.visitor+' '+r.message+' '+r.answer).toLowerCase().includes(q))){const d=node('details','');d.append(node('summary',new Date(row.time*1000).toLocaleString()+' · Session '+row.visitor+' · '+row.feature+(row.failed?' · Failed':'')));for(const [label,text] of [['Visitor',row.message],['Lucid',row.answer]]){d.append(node('h3',label));const p=node('div',text||'(No reply recorded)');p.className='chat-text';d.append(p);}$('chats').append(d);}if(!$('chats').children.length)$('chats').append(node('p','No matching activity yet.'));}
async function refresh(){const data=await request('action',{token,action:'dashboard'});$('host').textContent='AI is running on your PC';$('stats').replaceChildren(...[['Requests',data.requests],['Visitor sessions',data.visitors],['Failed requests',data.failures]].map(([label,value])=>{const d=node('div',label);d.className='metric';d.prepend(node('strong',String(value)));return d;}));$('features').replaceChildren(...Object.entries(data.features).map(([name,count])=>{const d=node('div',name);d.className='feature';d.append(node('strong',String(count)));return d;}));rows=data.activity;renderRows();$('status').textContent='Updated '+new Date().toLocaleTimeString()+'. Admin sign-in lasts 30 minutes.';}
async function run(fn){try{await fn();}catch(e){$('status').textContent=String(e.message||e);}}
function clear(){token='';rows=[];clearTimeout(timer);$('chats').replaceChildren();$('stats').replaceChildren();$('features').replaceChildren();$('dashboard').hidden=true;$('login').hidden=false;}
$('login').onsubmit=e=>{e.preventDefault();run(async()=>{const password=$('password').value;$('password').value='';token=(await request('login',{password})).token;await refresh();$('dashboard').hidden=false;$('login').hidden=true;timer=setTimeout(()=>{clear();$('status').textContent='Admin session expired. Sign in again.';},1800000);});};
$('logout').onclick=()=>run(async()=>{try{await request('action',{token,action:'logout'});}finally{clear();$('status').textContent='Signed out.';}});
$('refresh').onclick=()=>run(refresh);$('filter').oninput=renderRows;
try{const config=await fetch('./backend.json',{cache:'no-store',signal:AbortSignal.timeout(10000)}).then(r=>{if(!r.ok)throw Error('Local PC host is not configured.');return r.json();});const url=new URL(config.url);if(config.provider!=='local'||url.protocol!=='https:'||!url.hostname.endsWith('.trycloudflare.com')||url.username||url.password)throw Error('Invalid local host address.');apiBase=url.origin;const health=await fetch(apiBase+'/api/health',{signal:AbortSignal.timeout(12000)});if(!health.ok||(await health.json()).app!=='lucid-v5-public')throw Error('Your PC host is offline. Start it and reload this page.');$('sign-in').disabled=false;$('status').textContent='Sign in to manage Lucid on your PC.';}catch(e){$('status').textContent='PC admin is unavailable. '+String(e.message||e);}
